title: Sanjay # your name (or website title) here
logo: "/images/MyLogo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Have a good amount of mathematical intuition and knowledge in data handling, analysis and machine learning. Loves to explore and learn new things every day.
  <a href="https://www.linkedin.com/in/sanjayulsha/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal

google_analytics: UA-000000-0 # your Google Analytics tracking ID here
