title: Sanjay # your name (or website title) here
logo: "/images/MyLogo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Have been learning, working on some problems with personal interest in data science, machine learning for last 8 months that gave me a good amount of mathematical intuition for most of related concepts, applied the same that I've learnt. 
  <br><br>
  Currently working on some deep learning related stuff popular these days on Generative Adversarial Networks (GANs) and getting hands dirty with it for gaining intuition behind the Generative models. 
  <br><br>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
